language: python

python: "3.6"

cache: pip

sudo: required

services: docker

before_install: pip install flake8

# handled in the Docker image
install: true

before_script: flake8 -v .

script:
 - docker build -t crs4/tdm-notebooks .
 - docker run --rm --entrypoint ../check crs4/tdm-notebooks
